### ISSUE TITLE
Problem with running 0.10.x version of the images in distributed mode

### ISSUE THREAD

**Issue by karol-brejna-i** [karol-brejna-i/docker-locust#5]
When running in distributed mode, you'll get the following error:
```
master        | [2019-04-17 18:18:36,124] master/INFO/stdout: 1000 records read
master        | [2019-04-17 18:18:36,124] master/INFO/stdout:
master        | [2019-04-17 18:18:36,125] master/INFO/root: Waiting for slaves to be ready, 0 of 1 connected
master        | [2019-04-17 18:18:36,200] master/INFO/locust.runners: Client b'81269be90ff9_24c41e4b061f4e37acde0753d38cca38' reported as ready. Currently 1 clients ready to swarm.
master        | [2019-04-17 18:18:37,126] master/INFO/locust.runners: Sending hatch jobs to 1 ready clients
master        | [2019-04-17 18:18:37,127] master/INFO/stdout: on_master_start_hatching
master        | [2019-04-17 18:18:37,127] master/INFO/stdout:
master        | [2019-04-17 18:18:37,127] master/ERROR/stderr: Traceback (most recent call last):
master        | [2019-04-17 18:18:37,127] master/ERROR/stderr: File "/usr/local/bin/locust", line 10, in <module>
master        | [2019-04-17 18:18:37,128] master/ERROR/stderr:
master        | [2019-04-17 18:18:37,128] master/ERROR/stderr: sys.exit(main())
master        | [2019-04-17 18:18:37,128] master/ERROR/stderr:
master        | [2019-04-17 18:18:37,128] master/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/locust/main.py", line 505, in main
master        | [2019-04-17 18:18:37,129] master/ERROR/stderr:
master        | [2019-04-17 18:18:37,129] master/ERROR/stderr: runners.locust_runner.start_hatching(options.num_clients, options.hatch_rate)
master        | [2019-04-17 18:18:37,129] master/ERROR/stderr:
master        | [2019-04-17 18:18:37,129] master/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/locust/runners.py", line 310, in start_hatching
master        | [2019-04-17 18:18:37,130] master/ERROR/stderr:
master        | [2019-04-17 18:18:37,130] master/ERROR/stderr: self.server.send_to_client(Message("hatch", data, client.id))
master        | [2019-04-17 18:18:37,130] master/ERROR/stderr:
master        | [2019-04-17 18:18:37,130] master/ERROR/stderr: File "/usr/local/lib/python3.6/site-packages/locust/rpc/zmqrpc.py", line 15, in send_to_client
master        | [2019-04-17 18:18:37,130] master/ERROR/stderr:
master        | [2019-04-17 18:18:37,130] master/ERROR/stderr: self.socket.send_multipart([msg.node_id.encode(), msg.serialize()])
master        | [2019-04-17 18:18:37,130] master/ERROR/stderr:
master        | [2019-04-17 18:18:37,130] master/ERROR/stderr: AttributeError
master        | [2019-04-17 18:18:37,131] master/ERROR/stderr: :
master        | [2019-04-17 18:18:37,131] master/ERROR/stderr: 'bytes' object has no attribute 'encode'
master        | [2019-04-17 18:18:37,131] master/ERROR/stderr:
master exited with code 1
```

Images for version 0.9 and 0.11 work OK.

## To reproduce
Use for example  "grubykarol/locust:0.10.0-python3.6-alpine3.9" image to start master and slave (can use example from the repo: https://github.com/karol-brejna-i/docker-locust/blob/master/examples/docker-compose-distributed-headless.yml)

**Comment by karol-brejna-i** [comment]
As a workaround, use images for version 0.11

**Comment by karol-brejna-i** [comment]
0.10 is an ancient version now. I am closing the issue without resolution.
